import os
import logging
from dotenv import load_dotenv

# Load `.env` environment variables
load_dotenv()

from slack_bolt import App
from slack_bolt.adapter.socket_mode import SocketModeHandler
from anthropic import Anthropic

from vector_store import query_knowledge_base

logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s")
logger = logging.getLogger(__name__)

# ==========================================
# Initialization
# ==========================================
SLACK_BOT_TOKEN = os.environ.get("SLACK_BOT_TOKEN")
SLACK_APP_TOKEN = os.environ.get("SLACK_APP_TOKEN")

app = App(token=SLACK_BOT_TOKEN)
anthropic_client = Anthropic()

# ==========================================
# The Slash Command (/ask-buglerock)
# ==========================================
def synthesize_answer(query: str, chunks: list[str]) -> str:
    """Passes the ChromaDB chunks and user's question to Claude."""
    context = "\n\n---\n\n".join(chunks) if chunks else "No relevant meeting context found. Please be polite and let the user know you are ready to answer meeting questions, or just say hello back!"
    prompt = (
        f"You are BungleJungle, an expert AI assistant answering questions based on meeting transcripts.\n"
        f"Use the following transcribed excerpts to answer the user's question. If the user is just saying hello, be polite back.\n\n"
        f"<context>\n{context}\n</context>\n\n"
        f"User Question: {query}"
    )
    
    response = anthropic_client.messages.create(
        model="claude-haiku-4-5-20251001",
        max_tokens=1000,
        messages=[{"role": "user", "content": prompt}]
    )
    
    # Return the text generated by Claude
    return response.content[0].text

@app.command("/ask-bunglejungle")
def handle_ask_buglerock(ack, respond, command):
    """
    Listener for /ask-bunglejungle.
    1. Acknowledges within 3 seconds.
    2. Queries ChromaDB for top 3 chunks.
    3. Synthesizes an answer using Claude.
    4. Responds to the user.
    """
    # Acknowledge the command immediately to prevent Slack timeout
    ack("BungleJungle is reading...")

    user_query = command.get("text", "").strip()
    if not user_query:
        respond("Please provide a question, e.g., `/ask-buglerock What did we discuss with Acme last week?`")
        return

    logger.info(f"Received slack command query: {user_query}")

    try:
        # Get context from Vector Store
        chunks = query_knowledge_base(user_query, n_results=3)
        
        # --- ADDED FOR VISIBILITY: Print out the exact chunks we pulled from ChromaDB! ---
        logger.info(f"==== RETRIEVED {len(chunks)} CHUNKS FROM CHROMADB ====")
        for idx, chunk in enumerate(chunks):
            logger.info(f"Chunk {idx+1}: {chunk}")
        logger.info("======================================================")

        # We don't abort on empty chunks anymore, we let Claude be conversational
        # if there happens to be zero context (e.g. for greetings)

        # Generate answer with Claude
        answer = synthesize_answer(user_query, chunks)
        
        # Send back to standard Slack response
        respond(answer)
        
    except Exception as e:
        logger.error(f"Error processing command: {e}")
        respond("Sorry, I encountered an error while safely retrieving or processing that information.")


# ==========================================
# Block Kit UI (Follow-up Drafts)
# ==========================================
def send_draft_for_approval(channel_id: str, draft_text: str):
    """
    Sends a message using Slack's Block Kit formatting including the drafted
    email and interactive buttons to approve or edit the draft.
    """
    blocks = [
        {
            "type": "header",
            "text": {
                "type": "plain_text",
                "text": "📝 New Follow-up Email Draft Generated",
                "emoji": True
            }
        },
        {
            "type": "section",
            "text": {
                "type": "mrkdwn",
                "text": "Please review the drafted email below based on the recent meeting:"
            }
        },
        {
            "type": "section",
            "text": {
                "type": "mrkdwn",
                "text": f"```\n{draft_text}\n```"
            }
        },
        {
            "type": "actions",
            "elements": [
                {
                    "type": "button",
                    "text": {
                        "type": "plain_text",
                        "text": "Approve & Send",
                        "emoji": True
                    },
                    "style": "primary",
                    "value": "approved",
                    "action_id": "approve_draft"
                },
                {
                    "type": "button",
                    "text": {
                        "type": "plain_text",
                        "text": "Edit / Discard",
                        "emoji": True
                    },
                    "style": "danger",
                    "value": "edit_discard",
                    "action_id": "edit_draft"
                }
            ]
        }
    ]
    
    # Notice we're utilizing the initialized `app` token here globally
    app.client.chat_postMessage(
        channel=channel_id,
        text="New follow-up email draft requires your review.",
        blocks=blocks
    )


# Basic action listeners to acknowledge button presses so the bot doesn't throw a warning triangle in Slack
@app.action("approve_draft")
def handle_approve_draft(ack, body, logger):
    ack()
    logger.info("User clicked 'Approve & Send'.")
    # Stub for Phase 4

@app.action("edit_draft")
def handle_edit_draft(ack, body, logger):
    ack()
    logger.info("User clicked 'Edit / Discard'.")
    # Stub for Phase 4


# ==========================================
# Socket Mode Execution
# ==========================================
if __name__ == "__main__":
    if not SLACK_BOT_TOKEN or not SLACK_APP_TOKEN:
        logger.error("Missing SLACK_BOT_TOKEN or SLACK_APP_TOKEN. Cannot start SocketModeHandler.")
    else:
        logger.info("⚡️ Starting Slack Bolt App in Socket Mode...")
        handler = SocketModeHandler(app, SLACK_APP_TOKEN)
        handler.start()
